[server]
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base                     = "light"
backgroundColor          = "#f0ebe1"
secondaryBackgroundColor = "#e8e0d4"
primaryColor             = "#0d9488"
textColor                = "#2c2416"
font                     = "sans serif"
