[server]
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2563eb"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#e2e8f0"
textColor = "#0f172a"
font = "sans serif"
