[server]
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2563eb"
backgroundColor = "#1e293b"
secondaryBackgroundColor = "#263450"
textColor = "#f1f5f9"
font = "sans serif"
